# Generated by Django 4.2.3 on 2023-07-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrossingImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(verbose_name="Дата создания")),
                ("img", models.BinaryField(null=True)),
            ],
            options={
                "db_table": "pereval_images",
            },
        ),
        migrations.CreateModel(
            name="MountainCrossing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(verbose_name="Дата создания")),
                ("raw_data", models.JSONField(verbose_name="Сырые данные")),
                ("images", models.JSONField(verbose_name="Список изображений")),
            ],
            options={
                "db_table": "pereval_added",
            },
        ),
    ]
