# Generated by Django 4.2.3 on 2023-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mountaincrossing",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новое"),
                    ("pending", "В работе"),
                    ("accepted", "Принято"),
                    ("rejected", "Отказано"),
                ],
                default="new",
                max_length=16,
                verbose_name="Статус заявки",
            ),
        ),
    ]
